// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkGSCzJt_iDYKT6Hccp6dtHYPy42WhiSw',
    appId: '1:720193850695:web:5ca8ddcb13389b88941062',
    messagingSenderId: '720193850695',
    projectId: 'delivery-f8e93',
    authDomain: 'delivery-f8e93.firebaseapp.com',
    storageBucket: 'delivery-f8e93.firebasestorage.app',
    measurementId: 'G-TLR8TT7HRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD01fuOOc2sGJjGZyzKWj2xuDj8Z3oCThE',
    appId: '1:720193850695:android:94fbec6d825d9686941062',
    messagingSenderId: '720193850695',
    projectId: 'delivery-f8e93',
    storageBucket: 'delivery-f8e93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiApuvVNdeCOr-w2IGgXfjpv1zSwBoFrY',
    appId: '1:720193850695:ios:dce8b04f9b86561e941062',
    messagingSenderId: '720193850695',
    projectId: 'delivery-f8e93',
    storageBucket: 'delivery-f8e93.firebasestorage.app',
    iosBundleId: 'my.edu.tarumt.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiApuvVNdeCOr-w2IGgXfjpv1zSwBoFrY',
    appId: '1:720193850695:ios:dce8b04f9b86561e941062',
    messagingSenderId: '720193850695',
    projectId: 'delivery-f8e93',
    storageBucket: 'delivery-f8e93.firebasestorage.app',
    iosBundleId: 'my.edu.tarumt.delivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkGSCzJt_iDYKT6Hccp6dtHYPy42WhiSw',
    appId: '1:720193850695:web:45ee6bfc5347ec5e941062',
    messagingSenderId: '720193850695',
    projectId: 'delivery-f8e93',
    authDomain: 'delivery-f8e93.firebaseapp.com',
    storageBucket: 'delivery-f8e93.firebasestorage.app',
    measurementId: 'G-W3PF8C8P8M',
  );
}